print("What is your name?")
name= input()
print("What is your organization?")
ORG= input()
print("What is your contact information?")
CONTACT=input()
print("What is your access level?")
ACCESS= input()
print("Who is your issuer?")
Issuer= input()
print("+---------------------------------------------------------+")
print("|                 APEX ENTERTAINMENT PASS                 |")
print("+---------------------------------------------------------+")
print("| Attendee : " +  name.ljust(45) + "|" )
print("| ORG      : " +  ORG.ljust(45) + "|" )
print("| CONTACT  : " + CONTACT.ljust(45) + "|")
print("| ACCESS   : " + ACCESS.ljust(45) + "|")
print("| ISSUER   : " + Issuer.ljust(45) + "|")
print("+---------------------------------------------------------+")